### ISSUE TITLE
github releases requires a tag

### ISSUE THREAD

**Issue by subtogash** [farag2/ReVanced_Builder#4]
мне пишет github releases requires a tag в uploading

**Comment by farag2** [comment]
О чем речь вообще? Я же не телепат.

**Comment by Perets2207** [comment]
![Uploading Screenshot_20230625_012210_com.huawei.browser.jpg…]()

**Comment by subtogash** [comment]
не хочет создавать релиз в стадии Uploading пишет github releases requires a tag

**Comment by subtogash** [comment]
попробуй сам запусти workflow dispatch

**Comment by farag2** [comment]
Скрин?

**Comment by farag2** [comment]
> попробуй сам запусти workflow dispatch

У меня все работает.

**Comment by farag2** [comment]
> мне пишет github releases requires a tag в uploading

Вообще это означает, что сначала надо релиз создать. Напрямую триггерить не надо. После создания релиза все автоматом начнет собираться.
