### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by butalex11** [farag2/ReVanced_Builder#7]
brut.androlib.exceptions.AndrolibException: Apk doesn't contain either AndroidManifest.xml file or resources.arsc file

**Comment by farag2** [comment]
Via CI/CD?

**Comment by butalex11** [comment]
both in CI\CD and windows powershell

**Comment by farag2** [comment]
Yeah, found the error reason. Will fix soon.

**Comment by farag2** [comment]
Fixed for local compilation. Please check.

**Comment by butalex11** [comment]
> Fixed for local compilation. Please check.

local compilation is OK, thank you
