### ISSUE TITLE
The following content is not available on this app

### ISSUE THREAD

**Issue by n-r-w** [farag2/ReVanced_Builder#8]
Starting today, it gives the error "The following content is not available on this app"

**Comment by farag2** [comment]
The same for me. I don't know why...

**Comment by n-r-w** [comment]
Maybe the youtube version is outdated?

**Comment by farag2** [comment]
1 month old. Never 've seen before. Also patcher cannot patch the latest supported apk. What's going on???

**Comment by n-r-w** [comment]
I do not know the revanced build process, but apparently the latest version is 19-11-43:
https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-11-43-release

**Comment by farag2** [comment]
> I do not know the revanced build process, but apparently the latest version is 19-11-43: https://www.apkmirror.com/apk/google-inc/youtube/youtube-19-11-43-release

We cannot use the latest YT package, but the only latest supported by ReVanced.

**Comment by farag2** [comment]
I forcibly save the supported YT version: https://github.com/farag2/ReVanced_Builder/commit/778ede997480558703e7ab55c35564c349cfc672

It seems, the JSON i parse wasn't updated yet to add a new version. that's why I got those warnings. Короче, я опять в шоке. :) Now it fully works! Please check!

**Comment by n-r-w** [comment]
Redirects to GmsCore. It looks like the microg from your release is not supported

**Comment by farag2** [comment]
I know already. Will change the code later.

**Comment by n-r-w** [comment]
Works well with GmsCore, спасибо :)

**Comment by farag2** [comment]
И тебе не хворать)

**Comment by farag2** [comment]
https://github.com/farag2/ReVanced_Builder/commit/422427e0e88c36dade3fc3ece67d0c59e5172d11

**Comment by farag2** [comment]
Fully fixed: https://github.com/farag2/ReVanced_Builder/commits/main/
